<!DOCTYPE html>
<html>
<?php include __DIR__ . '/ex/header.phtml'; ?>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php include __DIR__ . '/ex/navbar.phtml'; ?>

    <?php include __DIR__ . '/ex/asider.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Article Creator</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/view/articles">Articles</a></li>
                            <li class="breadcrumb-item active">Article Editor</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <?php include __DIR__.'/ex/alertMessage.phtml';?>

                <div class=" content">

                    <div class="ui form">

                        <div class="field">

                            <label for="title">
                                Title
                            </label>
                            <input type="text" name="title" id="title" placeholder="please enter your Titile">

                        </div>

                        <div class="field">

                            <label for="author">
                                Author
                            </label>
                            <input type="text" name="author" id="author" placeholder="please enter your author"
                            value="纸色">

                        </div>

                        <div class="field">
                            <label for="type">
                                Type
                            </label>
                            <select name="type" id="type">
                                <?php
                                echo \Cms\Helper\TemplateHelper::generateSelectOptions(\Cms\Entity\Article::$types);
                                ?>
                            </select>

                        </div>

                        <div class="field">
                            <label for="status">
                                Status
                            </label>
                            <select name="status" id="status">
                                <?php
                                echo \Cms\Helper\TemplateHelper::generateSelectOptions(\Cms\Entity\Article::$statues);
                                ?>
                            </select>

                        </div>

                        <div class="field">
                            <label for="status">
                                DownloadUrl
                            </label>
                            <input type="text" name="downloadUrl" id="downloadUrl" placeholder="please enter your downloadUrl">
                        </div>

                        <div class="field">

                            <label for="content">
                                Content
                            </label>
                            <div name="content" id="content">
                                Enjoy your comment!
                            </div>

                        </div>

                    </div>

                </div>
                <div class="footer" style="padding-top: 1rem;">
                    <div class="ui animated button primary right floated" tabindex="0" id="submit">
                        <div class="visible content">Created</div>
                        <div class="hidden content">
                            <i class="right arrow icon"></i>
                        </div>
                    </div>
                </div>

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php include __DIR__ . '/ex/footer.phtml'; ?>
</div>
<!-- ./wrapper -->

<?php include __DIR__ . '/ex/scripts.phtml'; ?>
<?php include __DIR__ . '/ex/editor.phtml'; ?>

<script>

    $('div#content').froalaEditor({
        heightMin: 400,
        heightMax: 600,
        // Set the image upload parameter.
        imageUploadParam: 'singeFile',

        // Set the image upload URL.
        imageUploadURL: '/admin/metadata/upload',

        // Additional upload params.
        imageUploadParams: {type: 'image'},

        // Set request type.
        imageUploadMethod: 'POST',

        // Set max image size to 5MB.
        imageMaxSize: 5 * 1024 * 1024,

        // Allow to upload PNG and JPG.
        imageAllowedTypes: ['jpeg', 'jpg', 'png']
    }).on('froalaEditor.image.beforeUpload', function (e, editor, images) {
        // Return false if you want to stop the image upload.
        console.log("Return false if you want to stop the image upload.");
    })
        .on('froalaEditor.image.uploaded', function (e, editor, response) {
            // Image was uploaded to the server.
            console.log("Image was uploaded to the server.");
        })
        .on('froalaEditor.image.inserted', function (e, editor, $img, response) {
            // Image was inserted in the editor.
            console.log("Image was inserted in the editor.");
        })
        .on('froalaEditor.image.replaced', function (e, editor, $img, response) {
            // Image was replaced in the editor.
            console.log("Image was replaced in the editor.");
        })
        .on('froalaEditor.image.error', function (e, editor, error, response) {
            console.log(error);

        });

    $("div#submit").click(function () {
        if ($(this).hasClass('loading')) {
            console.log('loading...');
        } else {
            $(this).addClass('loading');
            console.log('click to ajax!');
            $.ajax({
                url: "/admin/article/add",
                type: 'POST',
                dataTye: 'json',
                data: getJsonData(),
                success: function (result) {
                    $("div#submit").removeClass('loading');
                    console.log(result);
                    window.location.href='/view/articles';
                },
                error: function (result) {
                    console.log(result);
                    $("div#submit").removeClass('loading');
                    var exception = result.responseJSON.exception;
                    if(exception){
                        $('#alert-message').append(exception);
                        $('#alert-message').removeClass('hidden');
                        $('#alert-message').addClass('show');
                    }
                }
            });
        }


    });

    function getJsonData() {
        var json = {
            'title': $('#title').val(),
            'author': $('#author').val(),
            'type': $('#type').val(),
            'status': $('#status').val(),
            'downloadUrl': $('#downloadUrl').val(),
            'content': $('div#content').froalaEditor('html.get')
        };

        return json;
    }

</script>

</body>
</html>

