<?php
/**
 * @var \Cms\Entity\MetaData $metadata
 */
?>
<!DOCTYPE html>
<html>
<?php include __DIR__ . '/ex/header.phtml'; ?>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php include __DIR__ . '/ex/navbar.phtml'; ?>

    <?php include __DIR__ . '/ex/asider.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Metadata Editor</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/view/metadatas">Metadatas</a></li>
                            <li class="breadcrumb-item active">Metadata Editor</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <?php include __DIR__ . '/ex/alertMessage.phtml'; ?>

                <div class=" content">
                    <form id="metadataForm">
                        <div class="ui form">

                            <input type="hidden" name="id" id="id" value="<?php echo $metadata->id; ?>">

                            <div class="field">

                                <label for="type">
                                    Type
                                </label>
                                <select name="type" id="type">
                                    <?php
                                    echo \Cms\Helper\TemplateHelper::generateSelectOptions(\Cms\Entity\MetaData::$types, $metadata->type);
                                    ?>
                                </select>
                            </div>

                            <div>
                                <label for="status">
                                    status
                                </label>
                                <select name="status" id="status">
                                    <?php
                                    echo \Cms\Helper\TemplateHelper::generateSelectOptions(\Cms\Entity\MetaData::$statues, $metadata->status);
                                    ?>
                                </select>
                            </div>

                            <div class="field">

                                <label for="downloadUrl">
                                    DownloadUrl
                                </label>
                                <img class="img-responsive " height="500px" src="<?php echo '/uploads/' . $metadata->downloadUrl; ?>" alt="downloadUrl">
                                <input type="file" name="singeFile" id="singeFile">
                            </div>

                        </div>
                    </form>

                </div>
                <div class="footer" style="padding-top: 1rem;">
                    <div class="ui animated button red left floated" tabindex="0" id="delete">
                        <div class="visible content">Deleted</div>
                        <div class="hidden content">
                            <i class="left arrow icon"></i>
                        </div>
                    </div>
                    <div class="ui animated button primary right floated" tabindex="0" id="submit">
                        <div class="visible content">Saved</div>
                        <div class="hidden content">
                            <i class="right arrow icon"></i>
                        </div>
                    </div>
                </div>

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php include __DIR__ . '/ex/footer.phtml'; ?>
</div>
<!-- ./wrapper -->

<?php include __DIR__ . '/ex/scripts.phtml'; ?>
<?php include __DIR__ . '/ex/deleteModal.phtml'; ?>

<script>

    $("div#submit").click(function () {
        if ($(this).hasClass('loading')) {
            console.log('loading...');
        } else {
            $(this).addClass('loading');
            console.log('click to ajax!');
            $.ajax({
                url: "/admin/metadata/edit/"+$('#id').val()+"?type="+$('#type').val(),
                type: 'POST',
                data: getJsonData(),
                //下面三个参数是上传文件 必须初始化的
                cache:false,
                processData:false,
                contentType:false,
                success: function (result) {
                    $("div#submit").removeClass('loading');
                    console.log(result);
                    window.location.reload();
                },
                error: function (result) {
                    $("div#submit").removeClass('loading');
                    console.log(result);
                    var exception = result.responseJSON.exception;
                    if (exception) {
                        $('#alert-message').append(exception);
                        $('#alert-message').removeClass('hidden');
                        $('#alert-message').addClass('show');
                    }
                }
            });
        }


    });

    function getJsonData() {
        return new FormData($('#metadataForm')[0]);
    };

    $('div#delete').click(function () {
        $('#delete-modal').modal('show');
    });

    $('#delete-sure').click(function () {
        $(this).attr('disabled', true);
        var id = $('#id').val();
        $.ajax({
            url: "/admin/metadata/remove",
            type: 'POST',
            dataType: 'json',
            data: {'id': id},
            success: function (result) {
                $('#delete-modal').modal('hide');
                window.location.href = '/view/metadatas';
            },
            error: function (result) {
                $('#delete-modal').modal("hide");
                console.log(result);
                var exception = result.responseJSON.exception;
                if (exception) {
                    $('#alert-message').append(exception);
                    $('#alert-message').removeClass('hidden');
                    $('#alert-message').addClass('show');
                }

            }
        });


    });

</script>

</body>
</html>

