<?php
/**
 * @var array $topNavigations
 */
?>
<!DOCTYPE html>
<html>
<?php include __DIR__ . '/ex/header.phtml'; ?>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php include __DIR__ . '/ex/navbar.phtml'; ?>

    <?php include __DIR__ . '/ex/asider.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Navigation Creator</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/view/navigations">Navigations</a></li>
                            <li class="breadcrumb-item active">Navigation Editor</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <?php include __DIR__.'/ex/alertMessage.phtml';?>

                <div class=" content">

                    <div class="ui form">

                        <div class="field">

                            <label for="name">
                                Name
                            </label>
                            <input type="text" name="name" id="name" placeholder="please enter your Name">

                        </div>

                        <div class="field">

                            <label for="zIndex">
                                zIndex
                            </label>
                            <select name="zIndex" id="zIndex">
                                <?php
                                echo \Cms\Helper\TemplateHelper::generateSelectOptions(\Cms\Entity\Navigation::$zIndexes);
                                ?>
                            </select>
                        </div>

                        <div class="field">
                            <label for="inheritId">
                                InheritId
                            </label>
                            <select name="inheritId" id="inheritId">
                                <option value="0">无</option>
                                <?php
                                echo \Cms\Helper\TemplateHelper::generateSelectOptions($topNavigations);
                                ?>
                            </select>

                        </div>

                        <div class="field">
                            <label for="href">
                                Href
                            </label>
                            <input type="text" name="href" id="href" placeholder="please enter your href">
                        </div>

                    </div>

                </div>
                <div class="footer" style="padding-top: 1rem;">
                    <div class="ui animated button primary right floated" tabindex="0" id="submit">
                        <div class="visible content">Created</div>
                        <div class="hidden content">
                            <i class="right arrow icon"></i>
                        </div>
                    </div>
                </div>

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php include __DIR__ . '/ex/footer.phtml'; ?>
</div>
<!-- ./wrapper -->

<?php include __DIR__ . '/ex/scripts.phtml'; ?>

<script>

    $("div#submit").click(function () {
        if ($(this).hasClass('loading')) {
            console.log('loading...');
        } else {
            $(this).addClass('loading');
            console.log('click to ajax!');
            $.ajax({
                url: "/admin/navigation/add",
                type: 'POST',
                dataTye: 'json',
                data: getJsonData(),
                success: function (result) {
                    $("div#submit").removeClass('loading');
                    console.log(result);
                    window.location.href='/view/navigations';
                },
                error: function (result) {
                    console.log(result);
                    $("div#submit").removeClass('loading');
                    var exception = result.responseJSON.exception;
                    if(exception){
                        $('#alert-message').append(exception);
                        $('#alert-message').removeClass('hidden');
                        $('#alert-message').addClass('show');
                    }
                }
            });
        }


    });

    function getJsonData() {
        var json = {
            'name': $('#name').val(),
            'zIndex': $('#zIndex').val(),
            'inheritId': $('#inheritId').val(),
            'href': $('#href').val(),
        };

        return json;
    }

</script>

</body>
</html>

