<?php
/** @var \Cms\Entity\Navigation $navigation
 * @var array $topNavigations
 */
?>

<!DOCTYPE html>
<html>
<?php include __DIR__ . '/ex/header.phtml'; ?>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php include __DIR__ . '/ex/navbar.phtml'; ?>

    <?php include __DIR__ . '/ex/asider.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Navigation Editor</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/view/navigations">Navigations</a></li>
                            <li class="breadcrumb-item active">Navigation Editor</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <?php include __DIR__ . '/ex/alertMessage.phtml'; ?>

                <div class=" content">

                    <div class="ui form">

                        <input type="hidden" name="id" id="id" value="<?php echo $navigation->id; ?>">

                        <div class="field">

                            <label for="name">
                                Name
                            </label>
                            <input type="text" name="name" id="name" placeholder="please enter your Name"
                                   value="<?php echo $navigation->name; ?>">

                        </div>
                        <div class="field">

                            <label for="zIndex">
                                zIndex
                            </label>
                            <select name="zIndex" id="zIndex">
                                <?php
                                echo \Cms\Helper\TemplateHelper::generateSelectOptions(\Cms\Entity\Navigation::$zIndexes, $navigation->zIndex);
                                ?>
                            </select>
                        </div>

                        <div class="field">
                            <label for="inheritId">
                                InheritId
                            </label>
                            <select name="inheritId" id="inheritId">
                                <option value="0">无</option>
                                <?php
                                echo \Cms\Helper\TemplateHelper::generateSelectOptions($topNavigations, $navigation->inheritId);
                                ?>
                            </select>

                        </div>

                        <div class="field">
                            <label for="href">
                                Href
                            </label>
                            <input type="text" name="href" id="href" placeholder="please enter your href"
                            value="<?php echo $navigation->href?>">
                        </div>

                    </div>

                </div>
                <div class="footer" style="padding-top: 1rem;">
                    <div class="ui animated button red left floated" tabindex="0" id="delete">
                        <div class="visible content">Deleted</div>
                        <div class="hidden content">
                            <i class="left arrow icon"></i>
                        </div>
                    </div>
                    <div class="ui animated button primary right floated" tabindex="0" id="submit">
                        <div class="visible content">Saved</div>
                        <div class="hidden content">
                            <i class="right arrow icon"></i>
                        </div>
                    </div>
                </div>

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php include __DIR__ . '/ex/footer.phtml'; ?>
</div>
<!-- ./wrapper -->

<?php include __DIR__ . '/ex/scripts.phtml'; ?>
<?php include __DIR__ . '/ex/deleteModal.phtml'; ?>

<script>


    $("div#submit").click(function () {
        if ($(this).hasClass('loading')) {
            console.log('loading...');
        } else {
            $(this).addClass('loading');
            console.log('click to ajax!');
            $.ajax({
                url: "/admin/navigation/edit",
                type: 'POST',
                dataTye: 'json',
                data: getJsonData(),
                success: function (result) {
                    $("div#submit").removeClass('loading');
                    console.log(result);
                },
                error: function (result) {
                    $("div#submit").removeClass('loading');
                    console.log(result);
                    var exception = result.responseJSON.exception;
                    if (exception) {
                        $('#alert-message').append(exception);
                        $('#alert-message').removeClass('hidden');
                        $('#alert-message').addClass('show');
                    }
                }
            });
        }


    });

    function getJsonData() {
        var json = {
            'id': $('#id').val(),
            'name': $('#name').val(),
            'zIndex': $('#zIndex').val(),
            'inheritId': $('#inheritId').val(),
            'href': $('#href').val(),
        };

        return json;
    };

    $('div#delete').click(function () {
        $('#delete-modal').modal('show');
    });

    $('#delete-sure').click(function () {
        $(this).attr('disabled', true);
        var id = $('#id').val();
        $.ajax({
            url: "/admin/navigation/remove",
            type: 'POST',
            dataType: 'json',
            data: {'id': id},
            success: function (result) {
                $('#delete-modal').modal('hide');
                window.location.href = '/view/navigations';
            },
            error: function (result) {
                $('#delete-modal').modal("hide");
                console.log(result);
                var exception = result.responseJSON.exception;
                if (exception) {
                    $('#alert-message').append(exception);
                    $('#alert-message').removeClass('hidden');
                    $('#alert-message').addClass('show');
                }

            }
        });


    });

</script>

</body>
</html>

