<!DOCTYPE html>
<html>
<?php include __DIR__ . '/ex/header.phtml'; ?>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php include __DIR__ . '/ex/navbar.phtml'; ?>

    <?php include __DIR__ . '/ex/asider.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">SellerIntentions</h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <table id="table" class="ui celled table hover cell-border" style="width: 100%">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>UserName</th>
                        <th>Phone</th>
                        <th>Address</th>
                        <th>IntentionType</th>
                        <th>Intention</th>
                        <th>AdditionType</th>
                        <th>Addition</th>
                        <th>Memo</th>
                        <th>IsHandle</th>
                        <th>CreateTime</th>
                        <th>UpdateTime</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>UserName</th>
                        <th>Phone</th>
                        <th>Address</th>
                        <th>IntentionType</th>
                        <th>Intention</th>
                        <th>AdditionType</th>
                        <th>Addition</th>
                        <th>Memo</th>
                        <th>IsHandle</th>
                        <th>CreateTime</th>
                        <th>UpdateTime</th>
                    </tr>
                    </tfoot>

                </table>

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php include __DIR__ . '/ex/footer.phtml'; ?>
</div>
<!-- ./wrapper -->

<?php include __DIR__ . '/ex/scripts.phtml'; ?>

<script>
    $(document).ready(function () {

        var table = $('#table').DataTable(
            {
                "scrollY": false,
                "scrollX": true,
                "ajax": "/admin/sellerIntentions",
                "columns": [
                    {"data": "id"},
                    {"data": "userName"},
                    {"data": "phone"},
                    {"data": "address"},
                    {"data": "intentionType"},
                    {"data": "intention"},
                    {"data": "additionType"},
                    {"data": "addition"},
                    {"data": "memo"},
                    {"data": "isHandle"},
                    {"data": "createTime.date"},
                    {"data": "updateTime.date"}
                ]
            }
        );
    });
</script>

</body>
</html>
