<!DOCTYPE html>
<html>
<?php include __DIR__ . '/ex/header.phtml'; ?>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <?php include __DIR__ . '/ex/navbar.phtml'; ?>

    <?php include __DIR__ . '/ex/asider.phtml'; ?>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">WechatUsers</h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <?php include __DIR__.'/ex/alertMessage.phtml';?>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">

                <table id="table" class="ui celled table hover cell-border" style="width: 100%">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>OpenId</th>
                        <th>NickName</th>
                        <th>Sex</th>
                        <th>Province</th>
                        <th>City</th>
                        <th>Country</th>
                        <th>HeadImgUrl</th>
                        <th>UnionId</th>
                        <th>CreateTime</th>
                        <th>UpdateTime</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>OpenId</th>
                        <th>NickName</th>
                        <th>Sex</th>
                        <th>Province</th>
                        <th>City</th>
                        <th>Country</th>
                        <th>HeadImgUrl</th>
                        <th>UnionId</th>
                        <th>CreateTime</th>
                        <th>UpdateTime</th>
                    </tr>
                    </tfoot>

                </table>

            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <?php include __DIR__ . '/ex/footer.phtml'; ?>
</div>
<!-- ./wrapper -->

<?php include __DIR__ . '/ex/scripts.phtml'; ?>

<script>
    $(document).ready(function () {

        var table = $('#table').DataTable(
            {
                "scrollY": false,
                "scrollX": true,
                "ajax": "/admin/wechatUsers",
                "columns": [
                    {"data": "id"},
                    {"data": "openid"},
                    {"data": "nickname"},
                    {"data": "sex"},
                    {"data": "province"},
                    {"data": "city"},
                    {"data": "country"},
                    {"data": "headImgUrl"},
                    {"data": "unionId"},
                    {"data": "createTime.date"},
                    {"data": "updateTime.date"}
                ],
                "columnDefs": [
                    {
                        "targets":3,
                        "render":function (data, type, full, meta) {

                            if(data == '1'){
                                return "男";
                            }

                            if(data == '0'){
                                return "女";
                            }

                            return data;

                        }
                    },
                    {
                        "targets":7,
                        "render":function (data, type, full, meta) {

                            return "<image src='"+data+"'>";

                        }
                    }

                ]
            }
        );


    });
</script>

</body>
</html>
