<!DOCTYPE html>
<html>
	<head>
	<title>纸色免费纸巾</title>
		<meta charset="UTF-8">
    	<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
		
		<link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
	    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.css"/>
	    <script src="/plugins/jquery/jquery.min.js"></script>
	    <script src="/plugins/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
	    <script src="/static/js/index.js"></script>
	</head>
	
	<style>
        img, body {
            padding: 0px;
            margin: 0px;
        }
        a{color:white;}
        a:hover{color:white;text-decoration: none;}

        #allmap {
            width: 100%;
            height: 100%;
            overflow: hidden;
            margin: 0;
            font-family: "微软雅黑";
        }

        .navSelect {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        /*.navbar-nav a{
            background-color: #000;
            opacity: 1;
            z-index: 4;
        }*/
        .nav-item span:hover {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .dropdown-item:hover {
            background-color: #6502F6;
        }

        .fa-angle:hover {
            background-color: #999 !important;
            color: #fff !important;
        }

        .transparent {
            background-color: rgba(0, 0, 0, 0.4); /* IE9、标准浏览器、IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂 */
        }
        .operation{
        	width: 20%;position: relative;
        }
        .operation_text{
        	position: absolute;bottom: 0;left:0;
        }
        .operation_font_150{
        	font-size: 150%;
        }
        .div_img:hover{
        	border-color: rgba(82, 168, 236, 1);
    		box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(102, 175, 233, 1);
    		color: darkseagreen;
        }
        .text_gray{opacity: 0.8;}

        @media \0screen\,screen\9 {
            /* 只支持IE6、7、8 */
            .transparent {
                background-color: #000000;
                filter: Alpha(opacity=40);
                position: static; /* IE6、7、8只能设置position:static(默认属性) ，否则会导致子元素继承Alpha值 */
                *zoom: 1; /* 激活IE6、7的haslayout属性，让它读懂Alpha */
            }

            .nav-link {
                position: relative; /* 设置子元素为相对定位，可让子元素不继承Alpha值 */
            }
        }

        @media screen and (max-width: 550px) {
            .angle_l, .angle_r {
                display: none !important;
            }
           .d-inline-block{width : 100%;}
        }

        @media screen and (min-width: 550px) {
            .angle_l, .angle_r {
                display: inline-block !important;
            }
           .d-inline-block{width : 19%;}
		   .img_div{top: 3500%;}
			.word_div{top:480%;}
			.foot_div{top:580%;}
        }
        @media screen and (min-width: 1400px) {
			.dropdown-menu{left: 53% !important;}
			.img_div{top: 5000%;}
			.word_div{top:650%;}
			.foot_div{top:750%;}
        }
    </style>
	<body onscroll="scroll()" style=" font-size: 70%;">

<nav id="header_2" class="navbar  navbar-light bg-faded pb-0 transparent "
     style="display:none;position: fixed;z-index: 3;width: 100%;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
            aria-label="Toggle navigation" style="margin:0 auto;">
        <span>
            <i class="fa fa-bars text-white"></i>
        </span>
    </button>
    <div class="collapse justify-content-center navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav text-center" style="font-size: 100%">
            <a href="/front/view/index" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">首页</span>
			</a>
			<a href="/front/view/adIntentionLook" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1 navSelect">广告合作</span>
			</a>
			<a href="/front/view/deviceInfo" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">产品展示</span>
			</a>
			<a href="/front/view/successList" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">成功案例</span>
			</a>
            <!--<a href="/front/view/team" class="nav-item nav-link text-white">-->
                <!--<span class="pl-1 pr-1 navSelect">团队资讯</span>-->
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span class="pl-1 pr-1">团队资讯</span>
				</a>
				<div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown1" style="opacity: 0.7;">
					<a href="/front/view/team" class="dropdown-item text-light text-center" href="#" style="font-size: 80%;">关于我们</a>
					<a href="/front/view/jobInfo" class="dropdown-item text-light text-center" href="#" style="font-size: 80%;">人才招聘</a>
				</div>
            <!--</a>-->
            <a href="/front/view/contact" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">联系我们</span>
            </a>
        </div>
    </div>
</nav>
<div style="position: relative;">
    <!-- 导航栏 -->
    <div id="header" class="text-center pt-3 transparent" style="position: absolute;z-index: 2;width:100%;">
        <div>
            <img src="/static/img/index/logo.png" class="img-responsive center-block" style="width:5rem;"/>
        </div>
        <div class="row m-0">
            <div class="col-sm-12">
                <nav class="navbar navbar-expand-sm navbar-toggler-md navbar-light bg-faded pb-0">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                            data-target="#navbarNavAltMarkup1" aria-controls="navbarNavAltMarkup1" aria-expanded="false"
                            aria-label="Toggle navigation" style="margin:0 auto;">
					    	<span>
					    		<i class="fa fa-bars text-white"></i>
					    	</span>
                    </button>
                    <div class="collapse justify-content-center navbar-collapse " id="navbarNavAltMarkup1">
                        <div class="navbar-nav text-center" style="font-size: 100%">
                            <a href="/front/view/index" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">首页</span>
                            </a>
                            <a href="/front/view/adIntentionLook" class="nav-item nav-link text-white">
								<span class="pl-1 pr-1 navSelect">广告合作</span>
							</a>
							<a href="/front/view/deviceInfo" class="nav-item nav-link text-white">
								<span class="pl-1 pr-1 ">产品展示</span>
							</a>
                            <a href="/front/view/successList" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">成功案例</span>
                            </a>
                            <!--<a class="nav-item nav-link text-white dropdown">-->
                                <!--<span class="pl-1 pr-1 navSelect">团队资讯</span>-->
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown12" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						        	<span class="pl-1 pr-1">团队资讯</span>
						        </a>
						        <div class="dropdown-menu badge-dark pt-0" aria-labelledby="navbarDropdown12" style="position: absolute;left:52% !important;opacity: 0.6;">
						          	<div style="height:4px; background-color: #6502F6;"></div>
						          	<div class="pl-1 pr-1">
							          	<a href="/front/view/team" class="dropdown-item text-light border-bottom pb-2 pl-0 pr-0 text-center" href="#" style="font-size: 60%;">关于我们</a>
							          	<a href="/front/view/jobInfo" class="dropdown-item text-light pt-2 pl-0 pr-0 text-center" href="#" style="font-size: 60%;">人才招聘</a>
						          	</div>
						        </div>
                            <!--</a>-->
                            <a href="/front/view/contact" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">联系我们</span>
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <div id="main_content">
        <img class="w-100" src="/static/img/operation/advertise.png">
    </div>
	<div>
		<div class="container-fluid pl-0" style="position:absolute;top:45%;">
			<div class="font-weight-bold text-center pt-4 pb-4" style="font-size: 240%;">
				<span class="font-weight-bold">多元化广告渠道</span><br />
				<span style="font-size: 50%;">Advertising cooperation</span>
			</div>
			<div class="row">
				<div class="col-sm-1 col-lg col-xl"></div>
				<div class="col-sm col-lg col-xl-2 pb-2">
					<div class="pt-5" style="position: absolute;">
						<img src="/static/img/operation/step-1.png" class="img-responsive center-block w-100 div_img"/>
						<div class="text-white pb-3 text-center" style="position: relative;z-index: 3;top:-70px;">
							<span class="font-weight-bold">液晶屏广告-CPM</span><br />
							<span class="text_gray">支持静/动态广告、巨大的广告空间</span><br />
							<span class="text_gray">挑战你的创意！</span>
						</div>
					</div>
				</div>
				<div class="col-sm col-lg col-xl-2 pb-2">
					<div class="pt-5" style="position: absolute;">
						<img src="/static/img/operation/step-2.png" class="img-responsive center-block w-100 div_img"/>
						<div class="text-white pb-3 text-center" style="position: relative;z-index: 3;top:-70px;">
							<span class="font-weight-bold">纸巾外包装广告-CPM</span><br />
							<span class="text_gray">“行走的广告”本身自带使用功能</span><br />
							<span class="text_gray">传播性广，时效性长</span>
						</div>
					</div>
				</div>
				<div class="col-sm col-lg col-xl-2 pb-2">
					<div class="pt-5" style="position: absolute;">
						<img src="/static/img/operation/step-3.png" class="img-responsive center-block w-100 div_img"/>
						<div class="text-white pb-3 text-center" style="position: relative;z-index: 3;top:-70px;">
							<span class="font-weight-bold">设备吸粉神器-CPA</span><br />
							<span class="text_gray">日增数十万粉丝不是梦！</span><br />
							<span>&nbsp;</span>
						</div>
					</div>
				</div>
				<div class="col-sm-1 col-lg col-xl"></div>
			</div>
			<div class="row text-center pb-3">
				<div class="col-sm col-lg col-xl"></div>
				<div class="col-sm col-lg col-xl-2 pb-2">
					<div class="pt-5 img_div" style="position: absolute;">
						<img src="/static/img/operation/step-4.png" class="img-responsive center-block w-100 div_img"/>
						<div class="text-white pb-3 text-center" style="position: relative;z-index: 3;top:-70px;">
							<span class="font-weight-bold">公众号推送-CPC</span><br/>
							<span class="text_gray">数百万粉丝关注度，广告信息</span><br/>
							<span>瞬时扩散</span>
						</div>
					</div>
				</div>
				<div class="col-sm col-lg col-xl-2 pb-2">
					<div class="pt-5 img_div" style="position: absolute;">
						<img src="/static/img/operation/step-5.png" class="img-responsive center-block w-100 div_img"/>
						<div class="text-white pb-3 text-center" style="position: relative;z-index: 3;top:-70px;">
							<span class="font-weight-bold">领纸成功界面-CPM</span><br />
							<span class="text_gray">日均百万领纸量页面等你加入！</span><br />
							<span>&nbsp;</span>
						</div>
					</div>
				</div>
				<div class="col-sm col-lg col-xl-2 pb-2">
					<div class="pt-5 img_div" style="position: absolute;">
						<img src="/static/img/operation/step-6.png" class="img-responsive center-block w-100 div_img"/>
						<div class="text-white pb-3 text-center" style="position: relative;z-index: 3;top:-70px;">
							<span class="font-weight-bold">机身广告-CPM</span><br />
							<span class="text_gray">目前只对战略伙伴开放</span><br />
							<span>&nbsp;</span>
						</div>
					</div>
				</div>
				<div class="col-sm col-lg col-xl"></div>
			</div>
			
			<div class="text-center font-weight-bold word_div w-100" style="color: #414141;opacity: 0.8;position: absolute;">
				<span>CPA导粉——————0.45元起</span><br /><br/>
				<span>多元广告渠道，场景包含全国一二线城市商圈、餐厅、娱乐场所</span><br />
				<span>旅游景区等人流密集点，广告投放更精准有效</span>
			</div>
			
<div class="container-fluid pb-5 foot_div" style="font-size: 100%;background-color: rgb(101,2,246);position:absolute;">
    <div class="container pl-0 pr-5 pt-5 text-white">
        <div class="row">
            <div class="col-6 border-right border-white pr-lg-4">
                <div class="float-lg-right">
                    <div class="row pb-1">
                        <span>全国咨询热线：</span>
                        <span>400-1399-330</span>
                    </div>
                    <div class="row pb-1">
                        <span>地址：</span>
                        <span>广州市海珠区黄埔古港历史文化景观区石基路528-2号首层</span>
                    </div>
                    <div class="row pb-1">
                        <span>商业咨询邮件：</span>
                        <span>IQGOGO@yeah.net</span>
                    </div>
                    <div class="row pb-1">
                        <span>客服热线：</span>
                        <span>180-2713-3575</span>
                    </div>
                    <div class="row pb-1">
                        <span>公司名称：</span>
                        <span>广州智谷科技有限责任公司</span>
                    </div>
                    <div class="row pb-1">
                        <span>工商登记号码：</span>
                        <span>563-81-00723</span>
                    </div>
                </div>
            </div>
            <div class="col-6 pl-lg-3">
                <div class="float-left pl-2">
                    <div class="row pb-1">
                        <span>Service hotline: </span>
                        <span>400-1399-330</span>
                    </div>
                    <div class="row pb-1">
                        <span>Address: </span>
                        <span>G/F, No.528-2, SHI JI Road, Haizhu district, Guangzhou</span>
                    </div>
                    <div class="row pb-1">
                        <span>E-mail: </span>
                        <span>IQgogo@yeah.net</span>
                    </div>
                    <div class="row pb-1">
                        <span>Company: </span>
                        <span>IQgogo Technology Co., Ltd</span>
                    </div>
                    <div class="row pt-2">
                        <i class="fa fa-weibo pr-2" style="font-size: 180%;"></i>
                        <i class="fa fa-qq pr-2" style="font-size: 180%;"></i>
                        <i class="fa fa-weixin" style="font-size: 180%;"></i>
                    </div>
                </div>
            </div>
            <div class="col-sm-2"></div>
        </div>
        <div class="text-center text-white pt-5 pb-3" style="font-size: 8px;">
            <span>Copyright 广州智谷科技有限公司All rights reserved. 粤ICP备16059531号-1</span>
        </div>
    </div>
</div>

		</div>
	</div>
</div>
<div class="modal fade" id="tips">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <i class="fa fa-smile-o text-danger fa-3x"></i>温馨提示
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body text-center">
                小猿正在努力开发中... ...
            </div>

            <!-- 模态框底部 -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
            </div>

        </div>
    </div>
</div>

		
	</body>
</html>
