<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">-->

    <link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.css"/>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/index.js"></script>
    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?78daa91ab6fd3c9f019bcd447e73b87e";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    <title>纸色免费纸巾</title>

    <style>
        img, body {
            padding: 0px;
            margin: 0px;
        }
        a{color:white;}
        a:hover{color:white;text-decoration: none;}

        #allmap {
            width: 100%;
            height: 100%;
            overflow: hidden;
            margin: 0;
            font-family: "微软雅黑";
        }

        .navSelect {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        /*.navbar-nav a{
            background-color: #000;
            opacity: 1;
            z-index: 4;
        }*/
        .nav-item span:hover {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .dropdown-item:hover {
            background-color: #6502F6;
        }

        .fa-angle:hover {
            background-color: #999 !important;
            color: #fff !important;
        }

        .transparent {
            background-color: rgba(0, 0, 0, 0.4); /* IE9、标准浏览器、IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂 */
        }

        @media \0screen\,screen\9 {
            /* 只支持IE6、7、8 */
            .transparent {
                background-color: #000000;
                filter: Alpha(opacity=40);
                position: static; /* IE6、7、8只能设置position:static(默认属性) ，否则会导致子元素继承Alpha值 */
                *zoom: 1; /* 激活IE6、7的haslayout属性，让它读懂Alpha */
            }

            .nav-link {
                position: relative; /* 设置子元素为相对定位，可让子元素不继承Alpha值 */
            }
        }

        @media screen and (max-width: 550px) {
            .angle_l, .angle_r {
                display: none !important;
            }
        }

        @media screen and (min-width: 550px) {
            .angle_l, .angle_r {
                display: inline-block !important;
            }
        }
    </style>
</head>
<body onscroll="scroll()" style=" font-size: 70%;">

<nav id="header_2" class="navbar  navbar-light bg-faded pb-0 transparent "
     style="display:none;position: fixed;z-index: 3;width: 100%;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
            aria-label="Toggle navigation" style="margin:0 auto;">
        <span>
            <i class="fa fa-bars text-white"></i>
        </span>
    </button>
    <div class="collapse justify-content-center navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav text-center" style="font-size: 100%">
            <a href="/front/view/index" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1 navSelect">首页</span>
			</a>
			<a href="/front/view/adIntentionLook" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">广告合作</span>
			</a>
			<a href="/front/view/deviceInfo" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">产品展示</span>
			</a>
			<a href="/front/view/successList" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">成功案例</span>
			</a>
            <!--<a href="/front/view/team" class="nav-item nav-link text-white">-->
                <!--<span class="pl-1 pr-1 navSelect">团队资讯</span>-->
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown12" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span class="pl-1 pr-1">团队资讯</span>
				</a>
				<div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown12" style="opacity: 0.7;">
					<a href="/front/view/team" class="dropdown-item text-light text-center" href="#" style="font-size: 80%;">关于我们</a>
					<a href="/front/view/jobInfo" class="dropdown-item text-light text-center" href="#" style="font-size: 80%;">人才招聘</a>
				</div>
            <!--</a>-->
            <a href="/front/view/contact" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">联系我们</span>
            </a>
        </div>
    </div>
</nav>
<div style="position: relative;">
    <!-- 导航栏 -->
    <div id="header" class="text-center pt-3 transparent" style="position: absolute;z-index: 2;width:100%;">
        <div>
            <img src="/static/img/index/logo.png" class="img-responsive center-block" style="width:5rem;"/>
        </div>
        <div class="row m-0">
            <div class="col-sm-12">
                <nav class="navbar navbar-expand-sm navbar-toggler-md navbar-light bg-faded pb-0">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                            data-target="#navbarNavAltMarkup1" aria-controls="navbarNavAltMarkup1" aria-expanded="false"
                            aria-label="Toggle navigation" style="margin:0 auto;">
					    	<span>
					    		<i class="fa fa-bars text-white"></i>
					    	</span>
                    </button>
                    <div class="collapse justify-content-center navbar-collapse " id="navbarNavAltMarkup1">
                        <div class="navbar-nav text-center" style="font-size: 100%">
                            <a href="/front/view/index" class="nav-item nav-link text-white">
								<span class="pl-1 pr-1 navSelect">首页</span>
							</a>
							<a href="/front/view/adIntentionLook" class="nav-item nav-link text-white">
								<span class="pl-1 pr-1">广告合作</span>
							</a>
							<a href="/front/view/deviceInfo" class="nav-item nav-link text-white">
								<span class="pl-1 pr-1">产品展示</span>
							</a>
							<a href="/front/view/successList" class="nav-item nav-link text-white">
								<span class="pl-1 pr-1">成功案例</span>
							</a>
                            <!--<a class="nav-item nav-link text-white dropdown">-->
                                <!--<span class="pl-1 pr-1 navSelect">团队资讯</span>-->
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						        	<span class="pl-1 pr-1">团队资讯</span>
						        </a>
						        <div class="dropdown-menu badge-dark pt-0" aria-labelledby="navbarDropdown1" style="position: absolute;left:52%;opacity: 0.6;">
						          	<div style="height:4px; background-color: #6502F6;"></div>
						          	<div class="pl-1 pr-1">
							          	<a href="/front/view/team" class="dropdown-item text-light border-bottom pb-2 pl-0 pr-0 text-center" href="#" style="font-size: 60%;">关于我们</a>
							          	<a href="/front/view/jobInfo" class="dropdown-item text-light pt-2 pl-0 pr-0 text-center" href="#" style="font-size: 60%;">人才招聘</a>
						          	</div>
						        </div>
                            <!--</a>-->
                            <a href="/front/view/contact" class="nav-item nav-link text-white" >
                                <span class="pl-1 pr-1">联系我们</span>
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
	
<!-- 文字轮播 -->
<div  style="background-color:rgba(0,0,0,0.7);position: absolute;z-index: 2;width:100%;bottom: 0;max-height: 25%;">
	<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
	  <div class="carousel-inner text-center">
		<div class="carousel-item active">
		    <div id="topDiv1" class = "pb-2 pt-2 d-inline-block text-left text-white">
				<span class="btn font-weight-bold pl-1 pr-1 mr-2" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>
				<a style="color: #aaa;" href = "http://dy.163.com/v2/article/detail/DJPPFE3T0518VS3S.html">[2018/06/08] 纸色已为全国范围内的华东、华南等四大区域提供维达纸巾。纸色衷心希望，能让大众放心！</a>
			</div><br />
			<div id="bottomDiv1" class = "pb-2 pt-2 d-inline-block text-left text-white">
				<span class="btn font-weight-bold pl-1 pr-1 mr-2" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>
				<a style="color: #aaa;" href = "http://dy.163.com/v2/article/detail/DK9DP95E0518VS3S.html">[2018/06/14] 希望通过对商务部的采访能让大家了解，在纸色免费纸巾的背后，有这样一群努力拼搏的人！</a>
			</div>
		</div>
		<div class="carousel-item">
			<div id="topDiv2" class = "pb-2 pt-2 d-inline-block text-left text-white">
				<span class="btn font-weight-bold pl-1 pr-1 mr-2" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>
				<a style="color: #aaa;" href = "http://dy.163.com/v2/article/detail/DLVN7N1S0518VS3S.html">[2018/07/06] 近期，越来越多的伙伴加入了纸色大家庭，团队成员的扩充使纸色的服务水平又有了新飞跃。</a>
			</div><br />
			<div id="bottomDiv2" class="pb-2 pt-2 d-inline-block text-left text-white">
				<span class="btn font-weight-bold pl-1 pr-1 mr-2" style="background-color: #00FF84;color:#6502F6;padding:0px;font-size: 60%;">HOT</span>
				<a style="color: #aaa;" href = "http://dy.163.com/v2/article/detail/DMJNRNAC0518VS3S.html">[2018/07/14] 纸色收到了「广州市中大社工服务中心」的奖项，以表彰纸色团队为公益事业所作出的努力。</a>
			</div>
		</div>
	  </div>
	  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	  </a>
	</div>
</div>
	
    <!-- 图片切换 -->
    <div id="main_content">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="/static/img/index/slide1.png?version=2018-8-10" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="/static/img/index/slide2.png" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="/static/img/index/slide3.png" alt="Third slide">
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pb-5" style="font-size: 100%;background-color: rgb(101,2,246);">
    <div class="container pl-5 pr-5 pt-5 text-white">
        <div class="row">
            <div class="col-6 border-right border-white pr-4">
                <div class="float-lg-right">
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 1px;">全国咨询热线:&nbsp;&nbsp;</span>
                        <span>400-1399-330</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 1px;">地址:&nbsp;&nbsp;</span>
                        <span>广州市海珠区黄埔古港历史文化景观区石基路528-2号首层</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 1px;">商业咨询邮件:&nbsp;&nbsp;</span>
                        <span>IQGOGO@yeah.net</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 1px;">客服热线:&nbsp;&nbsp;</span>
                        <span>180-2713-3575</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 1px;">公司名称:&nbsp;&nbsp;</span>
                        <span>广州智谷科技有限责任公司</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 1px;">工商登记号码:&nbsp;&nbsp;</span>
                        <span>563-81-00723</span>
                    </div>
                </div>
            </div>
            <div class="col-6 pl-lg-3">
                <div class="float-left pl-2">
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 0.5px;">Service hotline:&nbsp;&nbsp;</span>
                        <span>400-1399-330</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 0.5px;">Address:&nbsp;&nbsp;</span>
                        <span>G/F, No.528-2, SHI JI Road, Haizhu district, Guangzhou</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 0.5px;">E-mail:&nbsp;&nbsp;</span>
                        <span>IQgogo@yeah.net</span>
                    </div>
                    <div class="row pb-1">
                        <span class="font-weight-bold" style="letter-spacing: 0.5px;">Company:&nbsp;&nbsp;</span>
                        <span>IQgogo Technology Co., Ltd</span>
                    </div>
                    <div class="row pt-2">
                        <i class="fa fa-weibo pr-2" style="font-size: 180%;"></i>
                        <i class="fa fa-qq pr-2" style="font-size: 180%;"></i>
                        <i class="fa fa-weixin" style="font-size: 180%;"></i>
                    </div>
                </div>
            </div>
            <div class="col-sm-2"></div>
        </div>
        <div class="text-center text-white pt-5 pb-3" style="font-size: 8px;">
            <span>Copyright 广州智谷科技有限公司All rights reserved. 粤ICP备16059531号-1</span>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(function () {
        $("img").addClass("carousel-inner img-responsive img-rounded");
        $("#myCarousel").carousel({
		interval:3000,
		pause:false
		});
		
		// 设置div长度
		var len1 = $("#bottomDiv1").width();
		
		$("#topDiv1").css("width",len1);
		var timer = setInterval(function(){
			var len2 = $("#bottomDiv2").width();
			var lenTop2 = $("#topDiv2").width();
			if(len2 > 0 && lenTop2 != len2){
				$("#topDiv2").css("width",len2);
				clearTimeout(timer);
			}
		},101);
    });
</script>

</body>
</html>
