<?php
/**
 * @var string $active
 */
?>
<!-- 导航 -->
<div style="background-image: url('/static/img/bg/header-bg.png');background-position-y: 100px;">
    <div class="transparent">
        <div class="text-center pt-3">
            <img src="/static/img/index/logo.png" class="img-responsive center-block" style="width:5rem;"/>
        </div>
        <nav class=" navbar navbar-expand-sm navbar-toggler-md navbar-light bg-faded pb-0 transparent" style="background: none;">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation" style="margin:0 auto;">
			    	<span>
			    		<i class="fa fa-bars text-white"></i>
			    	</span>
            </button>
            <div class="collapse justify-content-center navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav text-center" style="font-size: 100%">
                    <a href="/front/view/index" class="nav-item nav-link text-white " >
                        <span class="pl-1 pr-1 <?php echo $active == 'index'?'navSelect':'';?>">首页</span>
                    </a>
                    <a href="/front/view/deviceInfo"  class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'deviceInfo'?'navSelect':'';?>">产品展示</span>
                    </a>
                    <a href="/front/view/adIntentionLook"  class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'adInetion'?'navSelect':'';?>">广告合作</span>
                    </a>
                    <a href="/front/view/successList" class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'success'?'navSelect':'';?>">成功案例</span>
                    </a>
                    <a href="/front/view/team" class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'team'?'navSelect':'';?>">团队资讯</span>
                    </a>
                    <a href="/front/view/contact" class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'contact'?'navSelect':'';?>">联系我们</span>
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>
