<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">-->


    <link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.css"/>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <script src="/plugins/bootstrap-4.1.1-dist/js/bootstrap.min.js"></script>
    <script src="/static/js/index.js"></script>

    <title>智谷科技</title>
    <style>
        img, body {
            padding: 0px;
            margin: 0px;
        }
        a{color:white;}
        a:hover{color:white;text-decoration: none;}

        #allmap {
            width: 100%;
            height: 100%;
            overflow: hidden;
            margin: 0;
            font-family: "微软雅黑";
        }

        .navSelect {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        /*.navbar-nav a{
            background-color: #000;
            opacity: 1;
            z-index: 4;
        }*/
        .nav-item span:hover {
            background-color: #6502F6;
            display: inline-block;
            border-radius: 3px;
        }

        .dropdown-item:hover {
            background-color: #6502F6;
        }

        .fa-angle:hover {
            background-color: #999 !important;
            color: #fff !important;
        }

        .transparent {
            background-color: rgba(0, 0, 0, 0.4); /* IE9、标准浏览器、IE6和部分IE7内核的浏览器(如QQ浏览器)会读懂 */
        }

        @media \0screen\,screen\9 {
            /* 只支持IE6、7、8 */
            .transparent {
                background-color: #000000;
                filter: Alpha(opacity=40);
                position: static; /* IE6、7、8只能设置position:static(默认属性) ，否则会导致子元素继承Alpha值 */
                *zoom: 1; /* 激活IE6、7的haslayout属性，让它读懂Alpha */
            }

            .nav-link {
                position: relative; /* 设置子元素为相对定位，可让子元素不继承Alpha值 */
            }
        }

        @media screen and (max-width: 550px) {
            .angle_l, .angle_r {
                display: none !important;
            }
        }

        @media screen and (min-width: 550px) {
            .angle_l, .angle_r {
                display: inline-block !important;
            }
        }
    </style>
</head>
<body onscroll="scroll()" style="font-size: 70%;">

<nav id="header_2" class="navbar  navbar-light bg-faded pb-0 transparent "
     style="display:none;position: fixed;z-index: 3;width: 100%;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
            aria-label="Toggle navigation" style="margin:0 auto;">
        <span>
            <i class="fa fa-bars text-white"></i>
        </span>
    </button>
    <div class="collapse justify-content-center navbar-collapse " id="navbarNavAltMarkup">
        <div class="navbar-nav text-center" style="font-size: 100%">
            <a href="/front/view/index" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1 navSelect">首页</span>
			</a>
			<a href="/front/view/adIntentionLook" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">广告合作</span>
			</a>
			<a href="/front/view/deviceInfo" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">产品展示</span>
			</a>
			<a href="/front/view/successList" class="nav-item nav-link text-white">
				<span class="pl-1 pr-1">成功案例</span>
			</a>
            <!--<a href="/front/view/team" class="nav-item nav-link text-white">-->
                <!--<span class="pl-1 pr-1 navSelect">团队资讯</span>-->
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown12" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span class="pl-1 pr-1">团队资讯</span>
				</a>
				<div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown12" style="opacity: 0.7;">
					<a href="/front/view/team" class="dropdown-item text-light text-center" href="#" style="font-size: 80%;">关于我们</a>
					<a href="/front/view/jobInfo" class="dropdown-item text-light text-center" href="#" style="font-size: 80%;">人才招聘</a>
				</div>
            <!--</a>-->
            <a href="/front/view/contact" class="nav-item nav-link text-white">
                <span class="pl-1 pr-1">联系我们</span>
            </a>
        </div>
    </div>
</nav>

<!-- 导航 -->
<div id="header" style="background-image: url('/static/img/bg/header-bg.png');background-position-y: 100px;">
    <div class="transparent">
        <div class="text-center pt-3">
            <img src="/static/img/index/logo.png" class="img-responsive center-block" style="width:5rem;"/>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggler-md navbar-light bg-faded pb-0 transparent" style="background: none;">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation" style="margin:0 auto;">
			    	<span>
			    		<i class="fa fa-bars text-white"></i>
			    	</span>
            </button>
            <div class="collapse justify-content-center navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav text-center" style="font-size: 100%">
                    <a href="/front/view/index" class="nav-item nav-link text-white " >
                        <span class="pl-1 pr-1 <?php echo $active == 'index'?'navSelect':'';?>">首页</span>
                    </a>
                    <a href="/front/view/adIntentionLook"  class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'adIntentionLook'?'navSelect':'';?>">广告合作</span>
                    </a>
                    <a href="/front/view/deviceInfo"  class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'deviceInfo'?'navSelect':'';?>">产品展示</span>
                    </a>
                    <a href="/front/view/successList" class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'success'?'navSelect':'';?>">成功案例</span>
                    </a>
                    <!--<a class="nav-item nav-link text-white dropdown">-->
                                <!--<span class="pl-1 pr-1 navSelect">团队资讯</span>-->
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						        	<span class="pl-1 pr-1">团队资讯</span>
						        </a>
						        <div class="dropdown-menu badge-dark pt-0" aria-labelledby="navbarDropdown12" style="position: absolute;left:52% !important;opacity: 0.6;">
						          	<div style="height:4px; background-color: #6502F6;"></div>
						          	<div class="pl-1 pr-1">
							          	<a href="/front/view/team" class="dropdown-item text-light border-bottom pb-2 pl-0 pr-0 text-center" href="#" style="font-size: 60%;">关于我们</a>
							          	<a href="/front/view/jobInfo" class="dropdown-item text-light pt-2 pl-0 pr-0 text-center" href="#" style="font-size: 60%;">人才招聘</a>
						          	</div>
						        </div>
                            <!--</a>-->
                    <a href="/front/view/contact" class="nav-item nav-link text-white" >
                        <span class="pl-1 pr-1 <?php echo $active == 'contact'?'navSelect':'';?>">联系我们</span>
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>

<!-- main body -->
<div id="main_content">
    <div class="container-fluid">
        <div class="row text-center pt-4">
            <h2 class="col-sm-12 font-weight-bold">多场景应用</h2>
            <p class="col-sm-12" style="font-size: 70%;">可满足多场景经营的可能性</p>
        </div>
        <div class="container-fluid pl-5 pr-5 pb-5">
            <div class="row text-center">
                <div class="col-sm col-lg col-xl"></div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success1.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success2.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success3.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl"></div>
            </div>
            <div class="row text-center">
                <div class="col-sm col-lg col-xl"></div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success4.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success5.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success6.jpg" class="img-responsive center-block" style="width: 95%;">
                </div>
                <div class="col-sm col-lg col-xl"></div>
            </div>
            <div class="row text-center">
                <div class="col-sm col-lg col-xl"></div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success7.jpg" class="img-responsive center-block"
                         style="width: 100%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success8.jpg" class="img-responsive center-block"
                         style="width: 100%;">
                </div>
                <div class="col-sm col-lg col-xl m-auto div-img pb-3">
                    <img src="/static/img/success/success9.jpg" class="img-responsive center-block"
                         style="width: 100%;">
                </div>
                <div class="col-sm col-lg col-xl"></div>
            </div>
        </div>
    </div>
    <!-- something -->
    <div class="pt-5 pb-5"
         style="background: url(/static/img/bg/bg-footer.png);-moz-background-size:100% 100%;background-size:100% 100%;background-repeat:no-repeat;">
        <div class="container">
            <div class="row text-center pl-5 pr-5">
                <div class="col-sm-2 "></div>
                <div class="col-sm-4 text-left row pl-5 pt-3">
                    <h6 class="font-weight-bold">体积小 投放快</h6>
                    <p style="font-size: 60%;">适用于商场、高校、旅游景点、车站、餐厅、运动场所、公厕等人流密集场所，满足广大民众用纸需求。
                    </p>
                </div>
                <div class="col-sm-1"></div>
                <div class="col-sm-4  pt-3 text-left">
                    <div class="pb-1">
                        <span class="font-weight-bold" style="font-size: 60%;">school district : 25%</span>
                        <div class="progress bg-white">
                            <div class="progress-bar bg-success progress-bar-1" role="progressbar" style="width: 25%"
                                 aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <div class="pb-1">
                        <span class="font-weight-bold" style="font-size: 60%;">Administrative Area : 25%</span>
                        <div class="progress bg-white">
                            <div class="progress-bar bg-success progress-bar-2" role="progressbar" style="width: 25%"
                                 aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                    <div class="pb-1">
                        <span class="font-weight-bold" style="font-size: 60%;">Dining area : 50%</span>
                        <div class="progress bg-white">
                            <div class="progress-bar bg-success progress-bar-3" role="progressbar" style="width: 50%"
                                 aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php include __DIR__ . '/../ex/page_footer.phtml'; ?>

    <script type="application/javascript" src="/static/js/main.js"></script>
</body>
</html>
