<html>

<head lang="en">
    <title>我参加了《纸色嘉年华》摄影作品展，快为我投上一票吧！</title>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0"/>
    <link rel="stylesheet" href="/plugins/bootstrap-4.1.1-dist/css/bootstrap.min.css">
    <script src="/plugins/jquery/jquery.min.js"></script>
    <style>
        .underline{
            text-decoration: underline;
        }
    </style>
</head>

<body class="container" style="background-image: url('http://pcdn.mikecrm.com/images/formTemplate/92_Bg.jpg'); background-position: center center; background-repeat: no-repeat; background-size: cover; background-color: rgb(255, 255, 255);background-attachment:fixed;">

<div class="card m-2" style="opacity: 0.9;">
    <div class="card-header text-center bg-white">
        <h5>纸色嘉年华</h5>
        <h5>"我纸钟意你,发现最美纸色瞬间"</h5>
        <h5 class="text-muted">摄影作品展</h5>
    </div>
    <div class="card-body">
        <div id="myCardHeader" class="row">
            <div class="col-3"></div>
            <div class="col border-top border-right border-left text-center " style="color: #0b2e13;">我的名次</div>
            <div class="col-3"></div>
        </div>
        <div class="card" id="myCard">
            <img class="card-img-top" src="http://img5.iqilu.com/c/u/2016/0504/1462326320241.jpg" alt="作品图片">
            <div class="card-body">
                <p class="card-text">第一名 5000票</p>
                <p class="card-text">编号：<span class="underline">a_20180723</span></p>
                <p class="card-text">作品名称：<span class="underline">城市喧哗下的纸巾机</span></p>
                <p class="card-text">作品描述：<span class="underline">城市喧哗中的纸巾机,位落天河城中万达广场中央,依傍美丽的广州塔。</span></p>
                <div class="text-center">
                    <button id="poll" class="btn btn-dark" style="background-color: #0b2e13;">&nbsp;为我投票&nbsp;</button>
                </div>
            </div>
        </div>

        <hr>
        <h5 class="text-center">
           排行榜
        </h5>

        <div class="card mt-3">
            <img class="card-img-top" src="http://img5.iqilu.com/c/u/2016/0504/1462326320241.jpg" alt="作品图片">
            <div class="card-body">
                <p class="card-text">第一名 5000票</p>
                <p class="card-text">编号：<span class="underline">a_20180723</span></p>
                <p class="card-text">作品名称：<span class="underline">城市喧哗下的纸巾机</span></p>
                <p class="card-text">作品描述：<span class="underline">城市喧哗中的纸巾机,位落天河城中万达广场中央,依傍美丽的广州塔。</span></p>
            </div>
        </div>
    </div>
</div>

</body>
<script>

    $(function () {
       $("#poll").click(function () {
          window.location.href = "/front/view/upWorks";
       });
    });

</script>

</html>