<!DOCTYPE html>
<html>
<?php include __DIR__ . '/../ex/head.phtml'; ?>
<body style="background-color: rgb(84,53,146);">
<div class="container-fluid">
    <div class="row d-lg-block" style="position: relative; top:-30px;">
        <img src="/static/img/questions.jpg" class="img-fluid" style="object-fit: fill;height: 8rem;"  >
    </div>
    <form>
        <div class="form-group">
            <label for="userName" class="text-white p-1">
                <i class="fa fa-pencil fa-fw"></i>
                姓 名
            </label>
            <input type="text" class="form-control" id="userName" placeholder="陈 X X ">
        </div>
        <div class="form-group">
            <label for="phone" class="text-white p-1">
                <i class="fa fa-pencil fa-fw"></i>
                联系方式
            </label>
            <input type="number" class="form-control" id="phone" placeholder="137XXXXX784">
        </div>
        <div class="form-group">
            <label for="qType" class="text-white p-1">
                <i class="fa fa-pencil fa-fw"></i>
                问题分类
            </label>
            <select class="form-control" id="qType">
                <option value="freeError">免费领取失败</option>
                <option value="paymentError">付费购买失败</option>
                <option value="codeError">机身二维码损坏</option>
                <option value="machineError">设备机身损坏</option>
            </select>
        </div>
        <div class="form-group">
            <label for="eId" class="text-white p-1">
                <i class="fa fa-pencil fa-fw"></i>
                设备唯一码
            </label>
            <input type="text" class="form-control" id="eId" placeholder="请填写设备二维码图下的一行代码">
        </div>
        <div class="form-group">
            <label for="wxId" class="text-white p-1">
                <i class="fa fa-pencil fa-fw"></i>
                微信ID
            </label>
            <input type="text" class="form-control" id="wxId" placeholder="查实后,我们将会退款到您的微信帐号">
        </div>
        <div class="form-group">
            <label for="advice" class="text-white p-1">
                <i class="fa fa-pencil fa-fw"></i>
                其他意见
            </label>
            <textarea class="form-control" id="advice" rows="4" placeholder="写上您宝贵的意见,谢谢您的支持!"></textarea>
        </div>
        <div class="form-group text-center">
            <button onclick="userFeedBack()" type="button" class="btn btn-primary btn-lg" >确定</button>
        </div>
    </form>
</div>
    <script src="/static/jquery-3.2.1.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="/plugins/bootstrap/js/bootstrap.js"></script>
    <script src="/static/koJS/knockout-3.4.2.js"></script>
    <script src="/static/koJS/knockout.mapping.js"></script>
    <script type="text/javascript" src="/dist/js/customerService/questions.js"></script>
</body>
</html>