<?php
/**
 * @var string $error
 * @var string $title
 */
?>
<!DOCTYPE html>
<html>
<?php include __DIR__ . '/../ex/head.phtml'; ?>
<body style="background-color: rgb(84,53,146);height: 100%;">
</body>
<div class="container-fluid">
    <div class="row d-lg-block" style="position: relative; top:-30px;">
        <img src="/static/img/questions.jpg" class="img-fluid" style="object-fit: fill;height: 8rem;">
    </div>

    <div class="text-center text-white">
        <div><i class="fa fa-check fa-5x "></i></div>
        <div class="mt-4"><label for="" class="text-bold"><?php echo $title;?></label></div>
        <div class="m-2"><?php echo $error;?></div>
        <div class="mt-4"><a id="close" class="btn btn-lg btn-outline-light col-6" href="javascript:window.opener=null;window.close();">确定</a></div>
    </div>

</div>


</html>