<?php
/**
 * @var string $info
 * @var string $title
 */
?>
<!DOCTYPE html>
<html>
<?php include __DIR__ . '/../ex/head.phtml'; ?>
<body style="background-color: rgb(84,53,146);height: 100%;">
</body>
<div class="container-fluid">
    <div class="row d-lg-block" style="position: relative; top:-30px;">
        <img src="/static/img/questions.jpg" class="img-fluid" style="object-fit: fill;height: 8rem;">
    </div>

    <div class="text-center text-white">
        <div><i class="fa fa-exclamation-circle fa-5x "></i></div>
        <div class="mt-4"><h3 for="" class="text-bold"><?php echo $title;?></h3></div>
        <div class="m-2" ><?php echo $info;?></div>
        <div class="mt-4"><button id="close" class="btn btn-lg btn-outline-light col-6" >确定</button></div>
    </div>

</div>

<script src="/plugins/jquery/jquery.min.js"></script>

<script>
    $('#close').click(function () {
        WeixinJSBridge.invoke('closeWindow',{},function(res){

            //alert(res.err_msg);

        });
        window.close();
    });

</script>

</html>