<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
    <link href="/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<!--    <link href="/dist/css/questions.css" rel="stylesheet" />-->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/plugins/font-awesome/css/font-awesome.min.css">
</head>